<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AnggotaKeluargaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => 1,
                'kartu_keluarga_id' => 1,
                'akun_id' => '1',
                'nama_lengkap' => 'KEVIN',
                'nik' => 1234567890123456,
                'jenis_kelamin' => 'PEREMPUAN',
                'tempat_lahir' => 'TONDO',
                'tanggal_lahir' => '1996-01-01',
                'agama' => 'ISLAM',
                'pendidikan' => 'SMA',
                'jenis_pekerjaan' => 'WIRAUSAHA',
                'golongan_darah' => 'A',
                'status_perkawinan' => 'KAWIN TERCATAT',
                'tanggal_perkawinan' => '2019-01-28',
                'status_hubungan_dalam_keluarga' => 'ISTRI',
                'kewarganegaraan' => 'WNI',
                'no_paspor' => '-',
                'no_kitap' => '-',
                'nama_ayah' => 'ILHAM',
                'nama_ibu' => 'MUJI',
                'alamat' => 'Jl. Mangga',
                'desa_kelurahan_id' => 7371100016,
                'kecamatan_id' => 7371100,
                'kabupaten_kota_id' => 7371,
                'provinsi_id' => 73,
                'foto_profil' => 'profil_default.png',
                'is_valid' => 1,
                'created_at' => now(),
            ],
            [
                'id' => 2,
                'kartu_keluarga_id' => 1,
                'akun_id' => '1',
                'nama_lengkap' => 'RIA',
                'nik' => 1234567890123456,
                'jenis_kelamin' => 'PEREMPUAN',
                'tempat_lahir' => 'TONDO',
                'tanggal_lahir' => '1996-01-01',
                'agama' => 'ISLAM',
                'pendidikan' => 'SMA',
                'jenis_pekerjaan' => 'WIRAUSAHA',
                'golongan_darah' => 'A',
                'status_perkawinan' => 'KAWIN TERCATAT',
                'tanggal_perkawinan' => '2019-01-28',
                'status_hubungan_dalam_keluarga' => 'ISTRI',
                'kewarganegaraan' => 'WNI',
                'no_paspor' => '-',
                'no_kitap' => '-',
                'nama_ayah' => 'ILHAM',
                'nama_ibu' => 'MUJI',
                'alamat' => 'Jl. Mangga',
                'desa_kelurahan_id' => 7371100016,
                'kecamatan_id' => 7371100,
                'kabupaten_kota_id' => 7371,
                'provinsi_id' => 73,
                'foto_profil' => 'profil_default.png',
                'is_valid' => 1,
                'created_at' => now(),
            ],
            [
                'id' => 3,
                'kartu_keluarga_id' => 1,
                'akun_id' => '1',
                'nama_lengkap' => 'LIDYA',
                'nik' => 9876554321123456,
                'jenis_kelamin' => 'PEREMPUAN',
                'tempat_lahir' => 'SILAE',
                'tanggal_lahir' => '2018-01-23',
                'agama' => 'ISLAM',
                'pendidikan' => 'TIDAK/BELUM SEKOLAH',
                'jenis_pekerjaan' => 'BELUM/TIDAK BEKERJA',
                'golongan_darah' => 'A',
                'status_perkawinan' => 'BELUM KAWIN',
                'tanggal_perkawinan' => NULL,
                'status_hubungan_dalam_keluarga' => 'ANAK',
                'kewarganegaraan' => 'WNI',
                'no_paspor' => '-',
                'no_kitap' => '-',
                'nama_ayah' => 'KEVIN',
                'nama_ibu' => 'RIA',
                'alamat' => 'Jl. Mangga',
                'desa_kelurahan_id' => 7371100016,
                'kecamatan_id' => 7371100,
                'kabupaten_kota_id' => 7371,
                'provinsi_id' => 73,
                'foto_profil' => 'profil_default.png',
                'is_valid' => 1,
                'created_at' => now(),
            ],
            [
                'id' => 4,
                'kartu_keluarga_id' => 1,
                'akun_id' => '1',
                'nama_lengkap' => 'AINI',
                'nik' => 9876554321123456,
                'jenis_kelamin' => 'PEREMPUAN',
                'tempat_lahir' => 'SILAE',
                'tanggal_lahir' => '2019-07-20',
                'agama' => 'ISLAM',
                'pendidikan' => 'TIDAK/BELUM SEKOLAH',
                'jenis_pekerjaan' => 'BELUM/TIDAK BEKERJA',
                'golongan_darah' => 'A',
                'status_perkawinan' => 'BELUM KAWIN',
                'tanggal_perkawinan' => NULL,
                'status_hubungan_dalam_keluarga' => 'ANAK',
                'kewarganegaraan' => 'WNI',
                'no_paspor' => '-',
                'no_kitap' => '-',
                'nama_ayah' => 'KEVIN',
                'nama_ibu' => 'RIA',
                'alamat' => 'Jl. Mangga',
                'desa_kelurahan_id' => 7371100016,
                'kecamatan_id' => 7371100,
                'kabupaten_kota_id' => 7371,
                'provinsi_id' => 73,
                'foto_profil' => 'profil_default.png',
                'is_valid' => 1,
                'created_at' => now(),
            ],
            [
                'id' => 5,
                'kartu_keluarga_id' => 1,
                'akun_id' => '1',
                'nama_lengkap' => 'VIDIA',
                'nik' => 9876554321123456,
                'jenis_kelamin' => 'PEREMPUAN',
                'tempat_lahir' => 'SILAE',
                'tanggal_lahir' => '2020-09-01',
                'agama' => 'ISLAM',
                'pendidikan' => 'TIDAK/BELUM SEKOLAH',
                'jenis_pekerjaan' => 'BELUM/TIDAK BEKERJA',
                'golongan_darah' => 'A',
                'status_perkawinan' => 'BELUM KAWIN',
                'tanggal_perkawinan' => NULL,
                'status_hubungan_dalam_keluarga' => 'ANAK',
                'kewarganegaraan' => 'WNI',
                'no_paspor' => '-',
                'no_kitap' => '-',
                'nama_ayah' => 'KEVIN',
                'nama_ibu' => 'RIA',
                'alamat' => 'Jl. Mangga',
                'desa_kelurahan_id' => 7371100016,
                'kecamatan_id' => 7371100,
                'kabupaten_kota_id' => 7371,
                'provinsi_id' => 73,
                'foto_profil' => 'profil_default.png',
                'is_valid' => 1,
                'created_at' => now(),
            ],
            [
                'id' => 6,
                'kartu_keluarga_id' => 1,
                'akun_id' => '1',
                'nama_lengkap' => 'FARA',
                'nik' => 9876554321123456,
                'jenis_kelamin' => 'PEREMPUAN',
                'tempat_lahir' => 'SILAE',
                'tanggal_lahir' => '2021-10-10',
                'agama' => 'ISLAM',
                'pendidikan' => 'TIDAK/BELUM SEKOLAH',
                'jenis_pekerjaan' => 'BELUM/TIDAK BEKERJA',
                'golongan_darah' => 'A',
                'status_perkawinan' => 'BELUM KAWIN',
                'tanggal_perkawinan' => NULL,
                'status_hubungan_dalam_keluarga' => 'ANAK',
                'kewarganegaraan' => 'WNI',
                'no_paspor' => '-',
                'no_kitap' => '-',
                'nama_ayah' => 'KEVIN',
                'nama_ibu' => 'RIA',
                'alamat' => 'Jl. Mangga',
                'desa_kelurahan_id' => 7371100016,
                'kecamatan_id' => 7371100,
                'kabupaten_kota_id' => 7371,
                'provinsi_id' => 73,
                'foto_profil' => 'profil_default.png',
                'is_valid' => 1,
                'created_at' => now(),
            ],

            // Kartu Keluarga 2
            [
                'id' => 7,
                'kartu_keluarga_id' => 2,
                'akun_id' => '1',
                'nama_lengkap' => 'RANGGA',
                'nik' => 1234567890123456,
                'jenis_kelamin' => 'PEREMPUAN',
                'tempat_lahir' => 'NUNU',
                'tanggal_lahir' => '1993-01-01',
                'agama' => 'ISLAM',
                'pendidikan' => 'SMA',
                'jenis_pekerjaan' => 'KARYAWAN SWASTA',
                'golongan_darah' => 'O',
                'status_perkawinan' => 'KAWIN TERCATAT',
                'tanggal_perkawinan' => '2018-02-22',
                'status_hubungan_dalam_keluarga' => 'ISTRI',
                'kewarganegaraan' => 'WNI',
                'no_paspor' => '-',
                'no_kitap' => '-',
                'nama_ayah' => 'RUDI',
                'nama_ibu' => 'MAYA',
                'alamat' => 'Jl. Mangga',
                'desa_kelurahan_id' => 7371100016,
                'kecamatan_id' => 7371100,
                'kabupaten_kota_id' => 7371,
                'provinsi_id' => 73,
                'foto_profil' => 'profil_default.png',
                'is_valid' => 1,
                'created_at' => now(),
            ],
            [
                'id' => 8,
                'kartu_keluarga_id' => 2,
                'akun_id' => '1',
                'nama_lengkap' => 'LINDA',
                'nik' => 1234567890123456,
                'jenis_kelamin' => 'PEREMPUAN',
                'tempat_lahir' => 'NUNU',
                'tanggal_lahir' => '1993-01-01',
                'agama' => 'ISLAM',
                'pendidikan' => 'SMA',
                'jenis_pekerjaan' => 'KARYAWAN SWASTA',
                'golongan_darah' => 'O',
                'status_perkawinan' => 'KAWIN TERCATAT',
                'tanggal_perkawinan' => '2018-02-22',
                'status_hubungan_dalam_keluarga' => 'ISTRI',
                'kewarganegaraan' => 'WNI',
                'no_paspor' => '-',
                'no_kitap' => '-',
                'nama_ayah' => 'RUDI',
                'nama_ibu' => 'MAYA',
                'alamat' => 'Jl. Mangga',
                'desa_kelurahan_id' => 7371100016,
                'kecamatan_id' => 7371100,
                'kabupaten_kota_id' => 7371,
                'provinsi_id' => 73,
                'foto_profil' => 'profil_default.png',
                'is_valid' => 1,
                'created_at' => now(),
            ],
            [
                'id' => 9,
                'kartu_keluarga_id' => 2,
                'akun_id' => '1',
                'nama_lengkap' => 'NANA',
                'nik' => 9876554321123456,
                'jenis_kelamin' => 'PEREMPUAN',
                'tempat_lahir' => 'PETOBO',
                'tanggal_lahir' => '2016-01-25',
                'agama' => 'ISLAM',
                'pendidikan' => 'TIDAK/BELUM SEKOLAH',
                'jenis_pekerjaan' => 'BELUM/TIDAK BEKERJA',
                'golongan_darah' => 'O',
                'status_perkawinan' => 'BELUM KAWIN',
                'tanggal_perkawinan' => NULL,
                'status_hubungan_dalam_keluarga' => 'ANAK',
                'kewarganegaraan' => 'WNI',
                'no_paspor' => '-',
                'no_kitap' => '-',
                'nama_ayah' => 'RANGGA',
                'nama_ibu' => 'LINDA',
                'alamat' => 'Jl. Mangga',
                'desa_kelurahan_id' => 7371100016,
                'kecamatan_id' => 7371100,
                'kabupaten_kota_id' => 7371,
                'provinsi_id' => 73,
                'foto_profil' => 'profil_default.png',
                'is_valid' => 1,
                'created_at' => now(),
            ],
            [
                'id' => 10,
                'kartu_keluarga_id' => 2,
                'akun_id' => '1',
                'nama_lengkap' => 'HARITH',
                'nik' => 9876554321123456,
                'jenis_kelamin' => 'LAKI-LAKI',
                'tempat_lahir' => 'MAMBORO',
                'tanggal_lahir' => '2017-10-30',
                'agama' => 'ISLAM',
                'pendidikan' => 'TIDAK/BELUM SEKOLAH',
                'jenis_pekerjaan' => 'BELUM/TIDAK BEKERJA',
                'golongan_darah' => 'A',
                'status_perkawinan' => 'BELUM KAWIN',
                'tanggal_perkawinan' => NULL,
                'status_hubungan_dalam_keluarga' => 'ANAK',
                'kewarganegaraan' => 'WNI',
                'no_paspor' => '-',
                'no_kitap' => '-',
                'nama_ayah' => 'RANGGA',
                'nama_ibu' => 'LINDA',
                'alamat' => 'Jl. Mangga',
                'desa_kelurahan_id' => 7371100016,
                'kecamatan_id' => 7371100,
                'kabupaten_kota_id' => 7371,
                'provinsi_id' => 73,
                'foto_profil' => 'profil_default.png',
                'is_valid' => 1,
                'created_at' => now(),
            ],
            [
                'id' => 11,
                'kartu_keluarga_id' => 2,
                'akun_id' => '1',
                'nama_lengkap' => 'FIKI',
                'nik' => 9876554321123456,
                'jenis_kelamin' => 'LAKI-LAKI',
                'tempat_lahir' => 'MAMBORO',
                'tanggal_lahir' => '2018-01-10',
                'agama' => 'ISLAM',
                'pendidikan' => 'TIDAK/BELUM SEKOLAH',
                'jenis_pekerjaan' => 'BELUM/TIDAK BEKERJA',
                'golongan_darah' => 'A',
                'status_perkawinan' => 'BELUM KAWIN',
                'tanggal_perkawinan' => NULL,
                'status_hubungan_dalam_keluarga' => 'ANAK',
                'kewarganegaraan' => 'WNI',
                'no_paspor' => '-',
                'no_kitap' => '-',
                'nama_ayah' => 'RANGGA',
                'nama_ibu' => 'LINDA',
                'alamat' => 'Jl. Mangga',
                'desa_kelurahan_id' => 7371100016,
                'kecamatan_id' => 7371100,
                'kabupaten_kota_id' => 7371,
                'provinsi_id' => 73,
                'foto_profil' => 'profil_default.png',
                'is_valid' => 1,
                'created_at' => now(),
            ],
            [
                'id' => 12,
                'kartu_keluarga_id' => 2,
                'akun_id' => '1',
                'nama_lengkap' => 'RISKI',
                'nik' => 9876554321123456,
                'jenis_kelamin' => 'LAKI-LAKI',
                'tempat_lahir' => 'MAMBORO',
                'tanggal_lahir' => '2019-03-11',
                'agama' => 'ISLAM',
                'pendidikan' => 'TIDAK/BELUM SEKOLAH',
                'jenis_pekerjaan' => 'BELUM/TIDAK BEKERJA',
                'golongan_darah' => 'A',
                'status_perkawinan' => 'BELUM KAWIN',
                'tanggal_perkawinan' => NULL,
                'status_hubungan_dalam_keluarga' => 'ANAK',
                'kewarganegaraan' => 'WNI',
                'no_paspor' => '-',
                'no_kitap' => '-',
                'nama_ayah' => 'RANGGA',
                'nama_ibu' => 'LINDA',
                'alamat' => 'Jl. Mangga',
                'desa_kelurahan_id' => 7371100016,
                'kecamatan_id' => 7371100,
                'kabupaten_kota_id' => 7371,
                'provinsi_id' => 73,
                'foto_profil' => 'profil_default.png',
                'is_valid' => 1,
                'created_at' => now(),
            ],
            [
                'id' => 13,
                'kartu_keluarga_id' => 2,
                'akun_id' => '1',
                'nama_lengkap' => 'FATIN',
                'nik' => 9876554321123456,
                'jenis_kelamin' => 'LAKI-LAKI',
                'tempat_lahir' => 'MAMBORO',
                'tanggal_lahir' => '2020-04-03',
                'agama' => 'ISLAM',
                'pendidikan' => 'TIDAK/BELUM SEKOLAH',
                'jenis_pekerjaan' => 'BELUM/TIDAK BEKERJA',
                'golongan_darah' => 'A',
                'status_perkawinan' => 'BELUM KAWIN',
                'tanggal_perkawinan' => NULL,
                'status_hubungan_dalam_keluarga' => 'ANAK',
                'kewarganegaraan' => 'WNI',
                'no_paspor' => '-',
                'no_kitap' => '-',
                'nama_ayah' => 'RANGGA',
                'nama_ibu' => 'LINDA',
                'alamat' => 'Jl. Mangga',
                'desa_kelurahan_id' => 7371100016,
                'kecamatan_id' => 7371100,
                'kabupaten_kota_id' => 7371,
                'provinsi_id' => 73,
                'foto_profil' => 'profil_default.png',
                'is_valid' => 1,
                'created_at' => now(),
            ],

        ];
        DB::table('anggota_keluarga')->insert($data);
    }
}
