<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AnggotaKeluargaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'kartu_keluarga_id' => 1,
                'akun_id' => '',
                'nama_lengkap' => 'NATALIA',
                'nik' => 1234567890123456,
                'jenis_kelamin' => 'PEREMPUAN',
                'tempat_lahir' => 'TONDO',
                'tanggal_lahir' => '1996-01-01',
                'agama' => 'ISLAM',
                'pendidikan' => 'SMA',
                'jenis_pekerjaan' => 'WIRAUSAHA',
                'golongan_darah' => 'A',
                'status_perkawinan' => 'KAWIN TERCATAT',
                'tanggal_perkawinan' => '2019-01-28',
                'status_hubungan_dalam_keluarga' => 'ISTRI',
                'kewarganegaraan' => 'WNI',
                'no_paspor' => '-',
                'no_kitap' => '-',
                'nama_ayah' => 'TIGREAL',
                'nama_ibu' => 'RUBY',
                'alamat_domisili' => 'Jl. Mangga',
                'desa_kelurahan_id' => 7373020003,
                'kecamatan_id' => 7373020,
                'kabupaten_kota_id' => 7373,
                'provinsi_id' => 73,
                'foto_ket_domisili' => '',
                'foto_ktp' => '',
                'foto_profil' => 'profil_default.png',
                'is_valid' => 1,
                'created_at' => now(),
            ],
            [
                'kartu_keluarga_id' => 1,
                'akun_id' => '',
                'nama_lengkap' => 'LYLIA',
                'nik' => 9876554321123456,
                'jenis_kelamin' => 'PEREMPUAN',
                'tempat_lahir' => 'SILAE',
                'tanggal_lahir' => '2021-01-23',
                'agama' => 'ISLAM',
                'pendidikan' => 'TIDAK/BELUM SEKOLAH',
                'jenis_pekerjaan' => 'BELUM/TIDAK BEKERJA',
                'golongan_darah' => 'A',
                'status_perkawinan' => 'BELUM KAWIN',
                'tanggal_perkawinan' => NULL,
                'status_hubungan_dalam_keluarga' => 'ANAK',
                'kewarganegaraan' => 'WNI',
                'no_paspor' => '-',
                'no_kitap' => '-',
                'nama_ayah' => 'GUSION',
                'nama_ibu' => 'NATALIA',
                'alamat_domisili' => 'Jl. Mangga',
                'desa_kelurahan_id' => 7373020003,
                'kecamatan_id' => 7373020,
                'kabupaten_kota_id' => 7373,
                'provinsi_id' => 73,
                'foto_ket_domisili' => '',
                'foto_ktp' => '',
                'foto_profil' => 'profil_default.png',
                'is_valid' => 1,
                'created_at' => now(),
            ],

            // Kartu Keluarga 2
            [
                'kartu_keluarga_id' => 2,
                'akun_id' => '',
                'nama_lengkap' => 'KARINA',
                'nik' => 1234567890123456,
                'jenis_kelamin' => 'PEREMPUAN',
                'tempat_lahir' => 'NUNU',
                'tanggal_lahir' => '1993-01-01',
                'agama' => 'ISLAM',
                'pendidikan' => 'SMA',
                'jenis_pekerjaan' => 'KARYAWAN SWASTA',
                'golongan_darah' => 'O',
                'status_perkawinan' => 'KAWIN TERCATAT',
                'tanggal_perkawinan' => '2018-02-22',
                'status_hubungan_dalam_keluarga' => 'ISTRI',
                'kewarganegaraan' => 'WNI',
                'no_paspor' => '-',
                'no_kitap' => '-',
                'nama_ayah' => 'BALMOND',
                'nama_ibu' => 'VEXANA',
                'alamat_domisili' => 'Jl. Mangga',
                'desa_kelurahan_id' => 7373020003,
                'kecamatan_id' => 7373020,
                'kabupaten_kota_id' => 7373,
                'provinsi_id' => 73,
                'foto_ket_domisili' => '',
                'foto_ktp' => '',
                'foto_profil' => 'profil_default.png',
                'is_valid' => 1,
                'created_at' => now(),
            ],
            [
                'kartu_keluarga_id' => 2,
                'akun_id' => '',
                'nama_lengkap' => 'NANA',
                'nik' => 9876554321123456,
                'jenis_kelamin' => 'PEREMPUAN',
                'tempat_lahir' => 'PETOBO',
                'tanggal_lahir' => '2021-01-25',
                'agama' => 'ISLAM',
                'pendidikan' => 'TIDAK/BELUM SEKOLAH',
                'jenis_pekerjaan' => 'BELUM/TIDAK BEKERJA',
                'golongan_darah' => 'O',
                'status_perkawinan' => 'BELUM KAWIN',
                'tanggal_perkawinan' => NULL,
                'status_hubungan_dalam_keluarga' => 'ANAK',
                'kewarganegaraan' => 'WNI',
                'no_paspor' => '-',
                'no_kitap' => '-',
                'nama_ayah' => 'ALUCARD',
                'nama_ibu' => 'KARINA',
                'alamat_domisili' => 'Jl. Mangga',
                'desa_kelurahan_id' => 7373020003,
                'kecamatan_id' => 7373020,
                'kabupaten_kota_id' => 7373,
                'provinsi_id' => 73,
                'foto_ket_domisili' => '',
                'foto_ktp' => '',
                'foto_profil' => 'profil_default.png',
                'is_valid' => 1,
                'created_at' => now(),
            ],
            [
                'kartu_keluarga_id' => 2,
                'akun_id' => '',
                'nama_lengkap' => 'HARITH',
                'nik' => 9876554321123456,
                'jenis_kelamin' => 'LAKI-LAKI',
                'tempat_lahir' => 'MAMBORO',
                'tanggal_lahir' => '2019-01-30',
                'agama' => 'ISLAM',
                'pendidikan' => 'TIDAK/BELUM SEKOLAH',
                'jenis_pekerjaan' => 'BELUM/TIDAK BEKERJA',
                'golongan_darah' => 'A',
                'status_perkawinan' => 'BELUM KAWIN',
                'tanggal_perkawinan' => NULL,
                'status_hubungan_dalam_keluarga' => 'ANAK',
                'kewarganegaraan' => 'WNI',
                'no_paspor' => '-',
                'no_kitap' => '-',
                'nama_ayah' => 'ALUCARD',
                'nama_ibu' => 'KARINA',
                'alamat_domisili' => 'Jl. Mangga',
                'desa_kelurahan_id' => 7373020003,
                'kecamatan_id' => 7373020,
                'kabupaten_kota_id' => 7373,
                'provinsi_id' => 73,
                'foto_ket_domisili' => '',
                'foto_ktp' => '',
                'foto_profil' => 'profil_default.png',
                'is_valid' => 1,
                'created_at' => now(),
            ],

        ];
        DB::table('anggota_keluarga')->insert($data);


        
    }
}
